// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0i_z_S2t2rk2abIpJy3331xn69cxLufY',
    appId: '1:103815002664:web:8693f62614a1eddb92931d',
    messagingSenderId: '103815002664',
    projectId: 'pet-connect-ed97a',
    authDomain: 'pet-connect-ed97a.firebaseapp.com',
    storageBucket: 'pet-connect-ed97a.firebasestorage.app',
    measurementId: 'G-LH9NCR11Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyeKb9fmfeLrPwKLHFekRfm9X7RbiFgV8',
    appId: '1:103815002664:android:95d8abc443726d7392931d',
    messagingSenderId: '103815002664',
    projectId: 'pet-connect-ed97a',
    storageBucket: 'pet-connect-ed97a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd7Xkp4yuHN48mOgT48EA8nbFUWaIGrgY',
    appId: '1:103815002664:ios:d319479e3f200de692931d',
    messagingSenderId: '103815002664',
    projectId: 'pet-connect-ed97a',
    storageBucket: 'pet-connect-ed97a.firebasestorage.app',
    iosBundleId: 'com.pet.connect.petConnect',
  );
}
